### ISSUE TITLE
Перемотка не работает при включенном плагине

### ISSUE THREAD

**Issue by LightTemplar** [serfreeman1337/ext_audio_loader#5]
Если видео было загружено при включенном плагине, то в нём не будет работает перемотка на нужную позицию - при каждой попытке перемотать проигрывание начинается с самого начала. 

VLC: 3.0.18
Kubuntu: 22.04

**Comment by LightTemplar** [comment]
Может проявиться не с первых секунд, а после проигрывания пары минут.

**Comment by serfreeman1337** [comment]
Такое наблюдается с форматом mka даже при [ручном добавлении трека](https://docs.videolan.me/vlc-user/3.0/en/advanced/player/external_audio_track.html).

Если вытащить трек из контейнера mka, например с помощью ffmpeg, то перемотка работает без проблем.
```
ffmpeg -i track.mka -vn -acodec copy track.ac3
```
где ac3 - расширение формата, который в контейнере


> https://code.videolan.org/videolan/vlc/-/issues/25625
> _It has been partially fixed in 4.0_

**Comment by LightTemplar** [comment]
Благодарю! Что ж, значит придется вытащить дорожку из контейнера.

**Comment by adminka-root** [comment]
К сожалению, я слишком рано сделал свой дополнительный костыль в Lua, аля:
`os.execute("find \"" .. dir .. "\" " .. "-type f,l -name \"*.mka\" -exec bash -c 'for f; do ffmpeg -i \"$f\" -vn -acodec copy \"${f%.*}.ac3\" && mv \"$f\" \"${f}.old\"; done' bash {} +")`

ведь даже с ac3 наблюдается та же проблема! Как исправить?
